package models

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// AfSymptom represents a row from 'dsaf.af_symptoms'.
type AfSymptom struct {
	ID       int       `json:"id"`       // id
	Name     string    `json:"name"`     // name
	Created  time.Time `json:"created"`  // created
	Modified time.Time `json:"modified"` // modified
	Deleted  int       `json:"deleted"`  // deleted
}

// Article represents a row from 'dsaf.articles'.
type Article struct {
	ID       int       `json:"id"`       // id
	Title    string    `json:"title"`    // title
	Content  string    `json:"content"`  // content
	URL      string    `json:"url"`      // url
	Created  time.Time `json:"created"`  // created
	Modified time.Time `json:"modified"` // modified
	Deleted  int       `json:"deleted"`  // deleted
}

// ArticleBrowsHistory represents a row from 'dsaf.article_brows_histories'.
type ArticleBrowsHistory struct {
	ID        int       `json:"id"`         // id
	UsersID   int64     `json:"users_id"`   // users_id
	ArticleID int       `json:"article_id"` // article_id
	Created   time.Time `json:"created"`    // created
	Modified  time.Time `json:"modified"`   // modified
	Deleted   int       `json:"deleted"`    // deleted
}

// DoseNotificationTime represents a row from 'dsaf.dose_notification_times'.
type DoseNotificationTime struct {
	ID       int       `json:"id"`        // id
	TimeName string    `json:"time_name"` // time_name
	Craeted  time.Time `json:"craeted"`   // craeted
	Modified time.Time `json:"modified"`  // modified
	Deleted  int       `json:"deleted"`   // deleted

}

// DosePattern represents a row from 'dsaf.dose_patterns'.
type DosePattern struct {
	ID          int       `json:"id"`           // id
	PatternName string    `json:"pattern_name"` // pattern_name
	Created     time.Time `json:"created"`      // created
	Modified    time.Time `json:"modified"`     // modified
	Deleted     int       `json:"deleted"`      // deleted

	// xo fields
	_exists, _deleted bool
}

// DoseStatus represents a row from 'dsaf.dose_status'.
type DoseStatus struct {
	ID         int       `json:"id"`          // id
	StatusName string    `json:"status_name"` // status_name
	Created    time.Time `json:"created"`     // created
	Modified   time.Time `json:"modified"`    // modified
	Deleted    int       `json:"deleted"`     // deleted
}

// DoseTiming represents a row from 'dsaf.dose_timings'.
type DoseTiming struct {
	ID         int       `json:"id"`          // id
	TimingName string    `json:"timing_name"` // timing_name
	Created    time.Time `json:"created"`     // created
	Modified   time.Time `json:"modified"`    // modified
	Deleted    int       `json:"deleted"`     // deleted
}

// DoseUnit represents a row from 'dsaf.dose_units'.
type DoseUnit struct {
	ID       int       `json:"id"`        // id
	UnitName string    `json:"unit_name"` // unit_name
	Created  time.Time `json:"created"`   // created
	Modified time.Time `json:"modified"`  // modified
	Deleted  int       `json:"deleted"`   // deleted
}

// Medicine represents a row from 'dsaf.medicines'.
type Medicine struct {
	ID                  int       `json:"id"`                    // id
	UserID              int64     `json:"user_id"`               // user_id
	MedicineID          string    `json:"medicine_id"`           // medicine_id
	PharmName           string    `json:"pharm_name"`            // pharm_name
	DosePatternID       int       `json:"dose_pattern_id"`       // dose_pattern_id
	DoseCount           int       `json:"dose_count"`            // dose_count
	DoseTimingID        int       `json:"dose_timing_id"`        // dose_timing_id
	DosePatternOriginal string    `json:"dose_pattern_original"` // dose_pattern_original
	Dose                float32   `json:"dose"`                  // dose
	DoseUnitID          int       `json:"dose_unit_id"`          // dose_unit_id
	Created             time.Time `json:"created"`               // created
	Modified            time.Time `json:"modified"`              // modified
	Deleted             int       `json:"deleted"`               // deleted
}

// MedicineSideEffect represents a row from 'dsaf.medicine_side_effects'.
type MedicineSideEffect struct {
	ID       int       `json:"id"`       // id
	Name     string    `json:"name"`     // name
	Created  time.Time `json:"created"`  // created
	Modified time.Time `json:"modified"` // modified
	Deleted  int       `json:"deleted"`  // deleted
}

// Symptom represents a row from 'dsaf.symptoms'.
type Symptom struct {
	ID                    int       `json:"id"`                       // id
	UserID                int64     `json:"user_id"`                  // user_id
	OnsetDate             time.Time `json:"onset_date"`               // onset_date
	AfSymptomID           int       `json:"af_symptom_id"`            // af_symptom_id
	MedicineSideEffectsID int       `json:"medicine_side_effects_id"` // medicine_side_effects_id
	Memo                  string    `json:"memo"`                     // memo
	Created               time.Time `json:"created"`                  // created
	Modified              time.Time `json:"modified"`                 // modified
	Deleted               int       `json:"deleted"`                  // deleted
}

// User represents a row from 'dsaf.users'.
type User struct {
	ID             int64     `json:"id"`               // id
	WelbyID        int64     `json:"welby_id"`         // welby_id
	KartePatientIt int64     `json:"karte_patient_it"` // karte_patient_it
	Created        time.Time `json:"created"`          // created
	Modified       time.Time `json:"modified"`         // modified
	Deleted        int       `json:"deleted"`          // deleted
}

// Vital represents a row from 'dsaf.vitals'.
type Vital struct {
	ID             int64     `json:"id"`               // id
	UsersID        int64     `json:"users_id"`         // users_id
	PatientVitalID int       `json:"patient_vital_id"` // patient_vital_id
	Created        time.Time `json:"created"`          // created
	Modified       time.Time `json:"modified"`         // modified
	Deleted        int       `json:"deleted"`          // deleted
}
